import type { Metadata } from "next";
import { Open_Sans, Amatic_SC } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-opens-sans",
  subsets: ["latin"],
});

const amaticSc = Amatic_SC({
  variable: "--font-amatic-sc",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${amaticSc.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
